#!/usr/bin/env python3
"""Wave-4 migration: flat collections → department sub-catalogs.

One-time (but idempotent) restructuring per the Portolan
nested-catalogs-flat-collections rule:

  catalog/<cid>/...          →  catalog/<group>/<cid>/...
  collection id "<cid>"      →  "<group>/<cid>"
  root catalog children      →  13 department catalogs
  new: catalog/<group>/catalog.json (+ README/AGENTS via later passes)

Structural links are rewritten here; everything else (checksums, themes,
styles, docs) is regenerated by the normal pipeline afterwards:
finalize → readme → agents → tests.
"""

import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from sources import SOURCES, GROUPS, GROUP_TITLES, GROUP_OF  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog"
PORTOLAN_SCHEMA = "https://schemas.portolan-sdi.org/portolan/v0.1.0/schema.json"

GROUP_DESCRIPTIONS = {
    "assessor": "Parcel fabric, historic parcels, sales, and the tax roll from the Assessor's Office.",
    "planning": "Boundaries, zoning, land use, historic designations, schools, and bike infrastructure from Planning and Urban Design.",
    "development": "Development incentives, districts, land bank inventory, and market analyses from SLDC and CDA.",
    "forestry": "Street and park tree inventories from the Forestry Division.",
    "streets": "Street network, permits, parking, and sweeping schedules from the Streets Department.",
    "parks": "City parks from the Parks Department.",
    "public-safety": "Police districts, sirens, crime, tornado damage, and flood controls.",
    "elections": "Precincts, polling centers, and election results from the Board of Election Commissioners.",
    "building": "Building-trade permit records from the Building Division.",
    "health": "Health department datasets.",
    "water": "Water Division service line inventory.",
    "community": "311 service requests and neighborhood organizations.",
    "citywide": "Citywide reference layers: the city boundary, floodplain, and ZIP codes.",
}


def move_collections() -> None:
    for cid in SOURCES:
        src = CATALOG / cid
        dst = CATALOG / GROUP_OF[cid] / cid
        if not src.exists() or dst.exists():
            continue
        # a group can share its name with a member collection (streets/streets)
        if GROUP_OF[cid] == cid:
            tmp = CATALOG / f".tmp_{cid}"
            shutil.move(str(src), str(tmp))
            dst.parent.mkdir(exist_ok=True)
            shutil.move(str(tmp), str(dst))
        else:
            dst.parent.mkdir(exist_ok=True)
            shutil.move(str(src), str(dst))
        print(f"moved {cid} -> {GROUP_OF[cid]}/{cid}")


def rewrite_collection(cid: str) -> None:
    group = GROUP_OF[cid]
    f = CATALOG / group / cid / "collection.json"
    if not f.exists():
        print(f"✗ missing {f}")
        return
    c = json.loads(f.read_text())
    c["id"] = f"{group}/{cid}"
    for l in c.get("links", []):
        if l["rel"] == "root":
            l["href"] = "../../catalog.json"
        elif l["rel"] == "parent":
            l["href"] = "../catalog.json"
            l["title"] = GROUP_TITLES[group]
    f.write_text(json.dumps(c, indent=2) + "\n")


def write_group_catalog(group: str) -> None:
    d = CATALOG / group
    children = [cid for cid in GROUPS[group] if (d / cid / "collection.json").exists()]
    cat = {
        "type": "Catalog",
        "id": group,
        "stac_version": "1.1.0",
        "stac_extensions": [PORTOLAN_SCHEMA],
        "title": GROUP_TITLES[group],
        "description": GROUP_DESCRIPTIONS[group],
        "links": [
            {"rel": "root", "href": "../catalog.json", "type": "application/json",
             "title": "City of St. Louis Open Data (Cloud-Native Mirror)"},
            {"rel": "parent", "href": "../catalog.json", "type": "application/json",
             "title": "City of St. Louis Open Data (Cloud-Native Mirror)"},
            {"rel": "describedby", "href": "./README.md", "type": "text/markdown"},
            {"rel": "agents", "href": "./AGENTS.md", "type": "text/markdown"},
        ] + [
            {"rel": "child", "href": f"./{cid}/collection.json",
             "type": "application/json", "title": SOURCES[cid]["title"]}
            for cid in children
        ],
    }
    (d / "catalog.json").write_text(json.dumps(cat, indent=2) + "\n")
    print(f"catalog for {group}: {len(children)} children")


def rewrite_root() -> None:
    f = CATALOG / "catalog.json"
    c = json.loads(f.read_text())
    keep = [l for l in c["links"] if l["rel"] not in ("child", "self")]
    c["links"] = keep + [
        {"rel": "child", "href": f"./{g}/catalog.json",
         "type": "application/json", "title": GROUP_TITLES[g]}
        for g in GROUPS
    ]
    f.write_text(json.dumps(c, indent=2) + "\n")
    print("root catalog rewritten: 13 department children")


def main() -> None:
    move_collections()
    for cid in SOURCES:
        rewrite_collection(cid)
    for group in GROUPS:
        write_group_catalog(group)
    rewrite_root()


if __name__ == "__main__":
    main()
