#!/usr/bin/env python3
"""Wave-4 migration: flat collections → department sub-catalogs.

One-time (but idempotent) restructuring per the Portolan
nested-catalogs-flat-collections rule:

  catalog/<cid>/...          →  catalog/<group>/<cid>/...
  collection id "<cid>"      →  "<group>/<cid>"
  root catalog children      →  13 department catalogs
  new: catalog/<group>/catalog.json (+ README/AGENTS via later passes)

Structural links are rewritten here; everything else (checksums, themes,
styles, docs) is regenerated by the normal pipeline afterwards:
finalize → readme → agents → tests.
"""

import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from sources import SOURCES, GROUPS, GROUP_TITLES, GROUP_OF, GROUP_CAPTIONS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog"
PORTOLAN_SCHEMA = "https://schemas.portolan-sdi.org/portolan/v0.1.0/schema.json"

GROUP_DESCRIPTIONS = {g: GROUP_CAPTIONS[g] for g in GROUPS}


def find_current(cid: str):
    """Locate the collection dir wherever it currently lives."""
    flat = CATALOG / cid
    if (flat / "collection.json").exists() or (flat / f"{cid}.parquet").exists():
        return flat
    hits = [p.parent for p in CATALOG.glob(f"*/{cid}/collection.json")]
    return hits[0] if hits else None


def move_collections() -> None:
    for cid in SOURCES:
        src = find_current(cid)
        dst = CATALOG / GROUP_OF[cid] / cid
        if src is None or src == dst or dst.exists():
            continue
        # a group can share its name with a member collection (streets/streets)
        if GROUP_OF[cid] == cid:
            tmp = CATALOG / f".tmp_{cid}"
            shutil.move(str(src), str(tmp))
            dst.parent.mkdir(exist_ok=True)
            shutil.move(str(tmp), str(dst))
        else:
            dst.parent.mkdir(exist_ok=True)
            shutil.move(str(src), str(dst))
        print(f"moved {cid} -> {GROUP_OF[cid]}/{cid}")


def rewrite_collection(cid: str) -> None:
    group = GROUP_OF[cid]
    f = CATALOG / group / cid / "collection.json"
    if not f.exists():
        print(f"✗ missing {f}")
        return
    c = json.loads(f.read_text())
    c["id"] = f"{group}/{cid}"
    for l in c.get("links", []):
        if l["rel"] == "root":
            l["href"] = "../../catalog.json"
        elif l["rel"] == "parent":
            l["href"] = "../catalog.json"
            l["title"] = GROUP_TITLES[group]
    f.write_text(json.dumps(c, indent=2) + "\n")


def write_group_catalog(group: str) -> None:
    d = CATALOG / group
    children = [cid for cid in GROUPS[group] if (d / cid / "collection.json").exists()]
    cat = {
        "type": "Catalog",
        "id": group,
        "stac_version": "1.1.0",
        "stac_extensions": [PORTOLAN_SCHEMA],
        "title": GROUP_TITLES[group],
        "description": GROUP_DESCRIPTIONS[group],
        "links": [
            {"rel": "root", "href": "../catalog.json", "type": "application/json",
             "title": "City of St. Louis Open Data (Cloud-Native Mirror)"},
            {"rel": "parent", "href": "../catalog.json", "type": "application/json",
             "title": "City of St. Louis Open Data (Cloud-Native Mirror)"},
            {"rel": "describedby", "href": "./README.md", "type": "text/markdown"},
            {"rel": "agents", "href": "./AGENTS.md", "type": "text/markdown"},
        ] + [
            {"rel": "child", "href": f"./{cid}/collection.json",
             "type": "application/json", "title": SOURCES[cid]["title"]}
            for cid in children
        ],
    }
    (d / "catalog.json").write_text(json.dumps(cat, indent=2) + "\n")
    print(f"catalog for {group}: {len(children)} children")


def rewrite_root() -> None:
    f = CATALOG / "catalog.json"
    c = json.loads(f.read_text())
    keep = [l for l in c["links"] if l["rel"] not in ("child", "self")]
    c["links"] = keep + [
        {"rel": "child", "href": f"./{g}/catalog.json",
         "type": "application/json", "title": GROUP_TITLES[g]}
        for g in GROUPS
    ]
    f.write_text(json.dumps(c, indent=2) + "\n")
    print("root catalog rewritten: 13 department children")


def remove_empty_old_groups() -> None:
    keep = set(GROUPS)
    for d in CATALOG.iterdir():
        if not d.is_dir() or d.name in keep or d.name.startswith((".", "_")):
            continue
        # old group dir: remove its catalog/readme/agents scaffolding if no
        # collections remain, then the dir itself
        if not any((c / "collection.json").exists() for c in d.iterdir() if c.is_dir()):
            shutil.rmtree(d)
            print(f"removed old group {d.name}")


def main() -> None:
    move_collections()
    remove_empty_old_groups()
    for cid in SOURCES:
        rewrite_collection(cid)
    for group in GROUPS:
        write_group_catalog(group)
    rewrite_root()


if __name__ == "__main__":
    main()
