"""Source manifest for the St. Louis open data mirror.

Single source of truth mapping each collection to where its data comes from.
Every dataset traces back to a page on https://www.stlouis-mo.gov/data/ —
`portal_page` is that page; extraction pulls from the city's ArcGIS servers
where a live service exists (better metadata + the city's own symbology),
otherwise from the portal's static download.
"""

PORTAL = "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id="

# type: "arcgis" → portolan extract arcgis --raw; "static" → download.sh
SOURCES = {
    "parcels": {
        "title": "Parcels",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/PARCELS_PUBLIC/MapServer",
        "layers": None,  # single-layer service
        "portal_page": PORTAL + "82",
        "department": "Assessor's Office",
    },
    "neighborhoods": {
        "title": "Neighborhood Boundaries",
        "type": "arcgis",
        "service": "https://maps6.stlouis-mo.gov/arcgis/rest/services/PublicDataStore/NEIGHBORHOOD_BOUNDARIES/FeatureServer",
        "layers": None,
        "portal_page": PORTAL + "85",
        "department": "Planning and Urban Design",
    },
    "wards": {
        "title": "Ward Boundaries (2020)",
        # The Hosted ward FeatureServer is incomplete (10 of 14 wards);
        # the portal's shapefile download has all 14.
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/planning/wards/wards_2020.zip",
        "portal_page": PORTAL + "131",
        "department": "Planning and Urban Design",
    },
    "city-boundary": {
        "title": "City Boundary",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/BOUNDARIES/MapServer",
        "layers": "City Limits",
        "portal_page": PORTAL + "67",
        "department": "Information Technology Services Agency",
    },
    "city-blocks": {
        "title": "City Blocks",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/BOUNDARIES/MapServer",
        "layers": "City Blocks",
        "portal_page": PORTAL + "12",
        "department": "Assessor's Office",
    },
    "streets": {
        "title": "City Streets",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Streets/FeatureServer",
        "layers": "STREETS",
        "portal_page": PORTAL + "68",
        "department": "Streets - Director's Office",
    },
    "parks": {
        "title": "City Parks",
        "type": "arcgis",
        "service": "https://maps9.stlouis-mo.gov/arcgis/rest/services/PARKS/Reservable_Park_Amenities/FeatureServer",
        "layers": "Parks",
        "portal_page": PORTAL + "46",
        "department": "Parks",
    },
    "police-districts": {
        "title": "Police District Boundaries",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/POLICE_DISTRICT/FeatureServer",
        "layers": None,
        "portal_page": PORTAL + "83",
        "department": "Police Department",
    },
    "election-precincts": {
        "title": "Election Wards & Precincts",
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/BOEC/Precincts_Current.zip",
        "portal_page": PORTAL + "124",
        "department": "Board of Election Commissioners",
    },
    "zoning": {
        "title": "Zoning",
        "type": "arcgis",
        "service": "https://maps9.stlouis-mo.gov/arcgis/rest/services/PDA/Zoning/MapServer",
        "layers": "Zoning",
        "portal_page": PORTAL + "78",
        "department": "Planning and Urban Design",
    },
    "historic-districts": {
        "title": "Historic Districts",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Historic_Districts/MapServer",
        "layers": None,
        "portal_page": PORTAL + "73",
        "department": "Planning and Urban Design",
    },
    "city-trees": {
        "title": "City Trees (Planting Sites)",
        "type": "arcgis",
        "service": "https://maps9.stlouis-mo.gov/arcgis/rest/services/FORESTRY/FORESTRY_TREES/MapServer",
        "layers": "CITY_TREES_ALL_SITES",
        "portal_page": PORTAL + "121",
        "department": "Forestry",
    },
    "tif-districts": {
        "title": "Tax Increment Financing (TIF) Districts",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/TIF_Districts/FeatureServer",
        "layers": "Districts TIF",
        "portal_page": PORTAL + "56",
        "department": "St. Louis Development Corporation",
    },
    "opportunity-zones": {
        "title": "Qualified Opportunity Zones",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Opportunity_Zones/FeatureServer",
        "layers": "Opportunity Zones",
        "portal_page": PORTAL + "59",
        "department": "St. Louis Development Corporation",
    },
    "lra-property": {
        "title": "LRA Property",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/SLDC_Real_Estate/FeatureServer",
        "layers": "LRA Inventory",
        "portal_page": PORTAL + "30",
        "department": "St. Louis Development Corporation",
    },
    "community-improvement-districts": {
        "title": "Community Improvement Districts (CIDs)",
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/SLDC/TAXING-DISTRICTS/CID/STLCIDs.geojson",
        "portal_page": PORTAL + "58",
        "department": "St. Louis Development Corporation",
    },
    "special-business-districts": {
        "title": "Special Business Districts (SBDs)",
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/SLDC/TAXING-DISTRICTS/SBD/STLSBDs_Shapefile.zip",
        "portal_page": PORTAL + "62",
        "department": "St. Louis Development Corporation",
    },
    "tax-abated-parcels": {
        "title": "Tax-abated Parcels",
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/SLDC/TAX-ABATEMENT/taxabatedparcels.geojson",
        "portal_page": PORTAL + "61",
        "department": "St. Louis Development Corporation",
    },
    "csb-311-requests": {
        "title": "CSB Service Requests (311)",
        "type": "static",
        "url": "https://www.stlouis-mo.gov/data/upload/data-files/csb.zip",
        "portal_page": PORTAL + "5",
        "department": "Neighborhood Stabilization / CSB",
    },
    "bike-infrastructure": {
        "title": "Bike Infrastructure",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Biking_Infrastructure_Map/MapServer",
        "layers": None,  # all five layers, merged with a source_layer column
        "portal_page": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Biking_Infrastructure_Map/MapServer",
        "department": "Planning and Urban Design",
    },
    "forest-park-trees": {
        "title": 'Forest Park Trees',
        "type": 'arcgis',
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/FORESTRY/FOREST_PARK_TREES/FeatureServer',
        "layers": 'FOREST_PARK_TREES',
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=123',
        "department": 'Forestry',
    },
    "siren-locations": {
        "title": 'Siren Locations',
        "type": 'arcgis',
        # maps6 STREETS/Sirens is stopped; the BPS firehouses+sirens service
        # carries the same siren points.
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/BPS/City_of_St__Louis_Firehouses_and_Outdoor_Warning_Sirens1/MapServer',
        "layers": 'Outdoor Warning Siren Locations',
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=132',
        "department": 'City Emergency Management Agency',
    },
    "schools": {
        "title": 'City Public Schools',
        "type": 'arcgis',
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Schools/FeatureServer',
        "layers": None,
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=125',
        "department": 'Planning and Urban Design',
    },
    "floodplain": {
        "title": 'Floodplain',
        "type": 'arcgis',
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/Floodplain/MapServer',
        "layers": None,
        "portal_page": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/Floodplain/MapServer',
        "department": 'Information Technology Services Agency',
    },
    "port-authority-district": {
        "title": 'Port Authority District',
        "type": 'arcgis',
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Port_Authority_District_Boundary/FeatureServer',
        "layers": None,
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=55',
        "department": 'St. Louis Development Corporation',
    },
    "wards-2010": {
        "title": 'Ward Boundaries (2010)',
        "type": 'static',
        "url": 'https://static.stlouis-mo.gov/open-data/planning/wards/wards_2010.zip',
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=131',
        "department": 'Planning and Urban Design',
    },
    "land-use": {
        "title": 'Strategic Land Use Plan',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Strategic_Land_Use_Plan/FeatureServer',
        "layers": None,
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=78',
        "department": 'Planning and Urban Design',
    },
    "lead-service-lines": {
        "title": 'Lead Service Line Inventory',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/STLWD_LSLI__Read_Only_View/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=80c69343cc2d418fb1796a342a863aac',
        "department": 'Water Division',
    },
    "market-value-analysis": {
        "title": '2024 Market Value Analysis',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/2024_Market_Value_Analysis/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=e71e3ebca1f345a4b7db134d30c5d9ff',
        "department": 'Community Development Administration',
    },
    "vacancy-composite": {
        "title": 'Parcel Vacancy Composite',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/SLDC_SLDC_Tol_Def_Vac_NP/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=98a6f429617546be9d9b467c5ad1dafc',
        "department": 'St. Louis Development Corporation',
    },
    "polling-places": {
        "title": 'Polling Centers',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Polling_Centers_WFL1/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=87bc5cf8db58428295792e690397ed75',
        "department": 'Board of Election Commissioners',
    },
    "election-results-nov-2024": {
        "title": 'November 2024 Election Results by Precinct',
        "type": 'arcgis',
        # the geocoded dve layer carries no attribute data; the vote-totals
        # table has the real per-precinct, per-contest results (tabular,
        # joins election-precincts by precinct name).
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Nov24_Detailed_Vote_Totals_Test/FeatureServer',
        "layers": None,
        "table": True,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=6e72fa855cd445f7af37d79615f602d0',
        "department": 'Board of Election Commissioners',
    },
    "tornado-damage-2025": {
        "title": 'May 2025 Tornado Damage',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/NS_Tornado_Map_WFL1/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=d2f73ad3cd2b434b91c6eacaef94df32',
        "department": 'City Emergency Management Agency',
    },
    "flood-controls": {
        "title": 'Flood Controls',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Flood_Controls_WFL1/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=4a08499ad4054caca42215e4c51aac0e',
        "department": 'Board of Public Service',
    },
    "neighborhood-organizations": {
        "title": 'Neighborhood Organizations',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Neighborhood_Organizations/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=ac198aeb9592458b8591c7258e719ad1',
        "department": 'Neighborhood Stabilization / CSB',
    },
    "property-taxes": {
        "title": 'Property Taxes',
        "type": "static",
        "url": 'https://www.stlouis-mo.gov/data/upload/data-files/prcl.zip',
        "portal_page": "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=3",
        "department": "Assessor's Office",
    },
    "electrical-permits": {
        "title": 'Electrical Permits',
        "type": "static",
        "url": 'https://www.stlouis-mo.gov/data/upload/data-files/electrical-permits.zip',
        "portal_page": "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=51",
        "department": 'Building Commissioner',
    },
    "mechanical-permits": {
        "title": 'Mechanical Permits',
        "type": "static",
        "url": 'https://www.stlouis-mo.gov/data/upload/data-files/mechanical-permits.zip',
        "portal_page": "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=52",
        "department": 'Building Commissioner',
    },
    "plumbing-permits": {
        "title": 'Plumbing Permits',
        "type": "static",
        "url": 'https://www.stlouis-mo.gov/data/upload/data-files/plumbing-permits.zip',
        "portal_page": "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=53",
        "department": 'Building Commissioner',
    },
    "street-permits": {
        "title": 'Street Permits',
        "type": "static",
        "url": 'https://www.stlouis-mo.gov/data/upload/data-files/streets/street-permits.csv',
        "portal_page": "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=17",
        "department": 'Streets - Street Division',
    },
    "occupancy-permits": {
        "title": 'Occupancy Permits',
        "type": "static",
        "url": 'https://www.stlouis-mo.gov/data/upload/data-files/occupancy-permits.zip',
        "portal_page": "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=6",
        "department": 'Building Commissioner',
    },
    "animal-bites": {
        "title": 'Animal Bites',
        "type": "static",
        "url": 'https://static.stlouis-mo.gov/open-data/HEALTH/ANIMAL-CONTROL/ANIMAL_BITES.csv',
        "portal_page": "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=130",
        "department": 'Environmental Health Services',
    },
    "parcels-history": {
        "title": "Parcels (Historical, 1997-2020)",
        "type": "static",
        "urls": ["https://www.stlouis-mo.gov/data/upload/data-files/stl_parcels_1997-2000.zip",
                 "https://www.stlouis-mo.gov/data/upload/data-files/stl_parcels_2001-2005.zip",
                 "https://www.stlouis-mo.gov/data/upload/data-files/stl_parcels_2006-2010.zip",
                 "https://www.stlouis-mo.gov/data/upload/data-files/stl_parcels_2011-2015.zip",
                 "https://www.stlouis-mo.gov/data/upload/data-files/stl_parcels_2016-2020.zip"],
        "url": "https://www.stlouis-mo.gov/data/upload/data-files/stl_parcels_1997-2000.zip",
        "portal_page": "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=82",
        "department": "Assessor's Office",
    },
    "crime": {
        "title": "Crime (NIBRS)",
        "type": "static",
        "url": "https://www.slmpd.org/crime_stats.shtml",
        "crime_scrape": True,
        "portal_page": "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=69",
        "department": "Metropolitan Police Department",
    },
    "historic-landmarks": {
        "title": "Historic Landmarks",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Historic_Landmarks/FeatureServer",
        "layers": "Historic Sites",
        "portal_page": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Historic_Landmarks/FeatureServer",
        "department": "Planning and Urban Design",
    },
    "zip-codes": {
        "title": "ZIP Codes",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/BOUNDARIES/MapServer",
        "layers": "Zip Codes",
        "portal_page": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/BOUNDARIES/MapServer",
        "department": "Information Technology Services Agency",
    },
    "parking-meters": {
        "title": "Parking Meters",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STREETS/ParkingServices/MapServer",
        "layers": "PARKING_METERS",
        "portal_page": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STREETS/ParkingServices/MapServer",
        "department": "Streets - Director's Office",
    },
    "street-sweeping": {
        "title": "Street Sweeping Schedule",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STREETS/Street_Sweeping/MapServer",
        "layers": "Street Sweeping Area Schedule",
        "portal_page": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STREETS/Street_Sweeping/MapServer",
        "department": "Streets - Street Division",
    },
    "business-licenses": {
        "title": "Business Licenses",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Business_Licenses_as_of_October_2025/FeatureServer",
        "layers": None,
        "portal_page": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Business_Licenses_as_of_October_2025/FeatureServer",
        "department": "St. Louis Development Corporation",
    },
    "tax-sales": {
        "title": "Tax Sales",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Tax_Sales/FeatureServer",
        "layers": "Tax Sales",
        "portal_page": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Tax_Sales/FeatureServer",
        "department": "St. Louis Development Corporation",
    },
    "property-sales": {
        "title": "Property Sales",
        "type": "static",
        "url": "https://www.stlouis-mo.gov/data/upload/data-files/prclsale.zip",
        "portal_page": PORTAL + "31",
        "department": "Assessor's Office",
    },
}


# ---------------------------------------------------------------------------
# Department sub-catalogs (wave 4). Collection ids become POSIX paths
# ("assessor/parcels") per the Portolan nested-catalogs-flat-collections rule.
# ---------------------------------------------------------------------------

GROUPS = {
    "assessor": ["parcels", "parcels-history", "city-blocks",
                 "property-sales", "property-taxes"],
    "planning": ["neighborhoods", "wards", "wards-2010", "zoning", "land-use",
                 "historic-districts", "historic-landmarks", "schools",
                 "bike-infrastructure"],
    "development": ["tif-districts", "opportunity-zones", "lra-property",
                    "community-improvement-districts",
                    "special-business-districts", "tax-abated-parcels",
                    "port-authority-district", "vacancy-composite",
                    "business-licenses", "tax-sales", "market-value-analysis"],
    "forestry": ["city-trees", "forest-park-trees"],
    "streets": ["streets", "street-permits", "parking-meters",
                "street-sweeping"],
    "parks": ["parks"],
    "public-safety": ["police-districts", "siren-locations",
                      "tornado-damage-2025", "flood-controls", "crime"],
    "elections": ["election-precincts", "polling-places",
                  "election-results-nov-2024"],
    "building": ["electrical-permits", "mechanical-permits",
                 "plumbing-permits", "occupancy-permits"],
    "health": ["animal-bites"],
    "water": ["lead-service-lines"],
    "community": ["csb-311-requests", "neighborhood-organizations"],
    "citywide": ["city-boundary", "floodplain", "zip-codes"],
}

GROUP_TITLES = {
    "assessor": "Assessor's Office",
    "planning": "Planning and Urban Design",
    "development": "Development (SLDC & CDA)",
    "forestry": "Forestry",
    "streets": "Streets",
    "parks": "Parks",
    "public-safety": "Public Safety",
    "elections": "Elections",
    "building": "Building Division",
    "health": "Health",
    "water": "Water Division",
    "community": "Community & Service Requests",
    "citywide": "Citywide Reference",
}

GROUP_OF = {cid: g for g, cids in GROUPS.items() for cid in cids}


def coll_rel(cid: str) -> str:
    """Collection directory path relative to the catalog root."""
    return f"{GROUP_OF[cid]}/{cid}"
