"""Source manifest for the St. Louis open data mirror.

Single source of truth mapping each collection to where its data comes from.
Every dataset traces back to a page on https://www.stlouis-mo.gov/data/ —
`portal_page` is that page; extraction pulls from the city's ArcGIS servers
where a live service exists (better metadata + the city's own symbology),
otherwise from the portal's static download.
"""

PORTAL = "https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id="

# type: "arcgis" → portolan extract arcgis --raw; "static" → download.sh
SOURCES = {
    "parcels": {
        "title": "Parcels",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/PARCELS_PUBLIC/MapServer",
        "layers": None,  # single-layer service
        "portal_page": PORTAL + "82",
        "department": "Assessor's Office",
    },
    "neighborhoods": {
        "title": "Neighborhood Boundaries",
        "type": "arcgis",
        "service": "https://maps6.stlouis-mo.gov/arcgis/rest/services/PublicDataStore/NEIGHBORHOOD_BOUNDARIES/FeatureServer",
        "layers": None,
        "portal_page": PORTAL + "85",
        "department": "Planning and Urban Design",
    },
    "wards": {
        "title": "Ward Boundaries (2020)",
        # The Hosted ward FeatureServer is incomplete (10 of 14 wards);
        # the portal's shapefile download has all 14.
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/planning/wards/wards_2020.zip",
        "portal_page": PORTAL + "131",
        "department": "Planning and Urban Design",
    },
    "city-boundary": {
        "title": "City Boundary",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/BOUNDARIES/MapServer",
        "layers": "City Limits",
        "portal_page": PORTAL + "67",
        "department": "Information Technology Services Agency",
    },
    "city-blocks": {
        "title": "City Blocks",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/BOUNDARIES/MapServer",
        "layers": "City Blocks",
        "portal_page": PORTAL + "12",
        "department": "Assessor's Office",
    },
    "streets": {
        "title": "City Streets",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Streets/FeatureServer",
        "layers": "STREETS",
        "portal_page": PORTAL + "68",
        "department": "Streets - Director's Office",
    },
    "parks": {
        "title": "City Parks",
        "type": "arcgis",
        "service": "https://maps9.stlouis-mo.gov/arcgis/rest/services/PARKS/Reservable_Park_Amenities/FeatureServer",
        "layers": "Parks",
        "portal_page": PORTAL + "46",
        "department": "Parks",
    },
    "police-districts": {
        "title": "Police District Boundaries",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/POLICE_DISTRICT/FeatureServer",
        "layers": None,
        "portal_page": PORTAL + "83",
        "department": "Police Department",
    },
    "election-precincts": {
        "title": "Election Wards & Precincts",
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/BOEC/Precincts_Current.zip",
        "portal_page": PORTAL + "124",
        "department": "Board of Election Commissioners",
    },
    "zoning": {
        "title": "Zoning",
        "type": "arcgis",
        "service": "https://maps9.stlouis-mo.gov/arcgis/rest/services/PDA/Zoning/MapServer",
        "layers": "Zoning",
        "portal_page": PORTAL + "78",
        "department": "Planning and Urban Design",
    },
    "historic-districts": {
        "title": "Historic Districts",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Historic_Districts/MapServer",
        "layers": None,
        "portal_page": PORTAL + "73",
        "department": "Planning and Urban Design",
    },
    "city-trees": {
        "title": "City Trees (Planting Sites)",
        "type": "arcgis",
        "service": "https://maps9.stlouis-mo.gov/arcgis/rest/services/FORESTRY/FORESTRY_TREES/MapServer",
        "layers": "CITY_TREES_ALL_SITES",
        "portal_page": PORTAL + "121",
        "department": "Forestry",
    },
    "tif-districts": {
        "title": "Tax Increment Financing (TIF) Districts",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/TIF_Districts/FeatureServer",
        "layers": "Districts TIF",
        "portal_page": PORTAL + "56",
        "department": "St. Louis Development Corporation",
    },
    "opportunity-zones": {
        "title": "Qualified Opportunity Zones",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Opportunity_Zones/FeatureServer",
        "layers": "Opportunity Zones",
        "portal_page": PORTAL + "59",
        "department": "St. Louis Development Corporation",
    },
    "lra-property": {
        "title": "LRA Property",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/SLDC_Real_Estate/FeatureServer",
        "layers": "LRA Inventory",
        "portal_page": PORTAL + "30",
        "department": "St. Louis Development Corporation",
    },
    "community-improvement-districts": {
        "title": "Community Improvement Districts (CIDs)",
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/SLDC/TAXING-DISTRICTS/CID/STLCIDs.geojson",
        "portal_page": PORTAL + "58",
        "department": "St. Louis Development Corporation",
    },
    "special-business-districts": {
        "title": "Special Business Districts (SBDs)",
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/SLDC/TAXING-DISTRICTS/SBD/STLSBDs_Shapefile.zip",
        "portal_page": PORTAL + "62",
        "department": "St. Louis Development Corporation",
    },
    "tax-abated-parcels": {
        "title": "Tax-abated Parcels",
        "type": "static",
        "url": "https://static.stlouis-mo.gov/open-data/SLDC/TAX-ABATEMENT/taxabatedparcels.geojson",
        "portal_page": PORTAL + "61",
        "department": "St. Louis Development Corporation",
    },
    "csb-311-requests": {
        "title": "CSB Service Requests (311)",
        "type": "static",
        "url": "https://www.stlouis-mo.gov/data/upload/data-files/csb.zip",
        "portal_page": PORTAL + "5",
        "department": "Neighborhood Stabilization / CSB",
    },
    "bike-infrastructure": {
        "title": "Bike Infrastructure",
        "type": "arcgis",
        "service": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Biking_Infrastructure_Map/MapServer",
        "layers": None,  # all five layers, merged with a source_layer column
        "portal_page": "https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Biking_Infrastructure_Map/MapServer",
        "department": "Planning and Urban Design",
    },
    "forest-park-trees": {
        "title": 'Forest Park Trees',
        "type": 'arcgis',
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/FORESTRY/FOREST_PARK_TREES/FeatureServer',
        "layers": 'FOREST_PARK_TREES',
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=123',
        "department": 'Forestry',
    },
    "siren-locations": {
        "title": 'Siren Locations',
        "type": 'arcgis',
        # maps6 STREETS/Sirens is stopped; the BPS firehouses+sirens service
        # carries the same siren points.
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/BPS/City_of_St__Louis_Firehouses_and_Outdoor_Warning_Sirens1/MapServer',
        "layers": 'Outdoor Warning Siren Locations',
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=132',
        "department": 'City Emergency Management Agency',
    },
    "schools": {
        "title": 'City Public Schools',
        "type": 'arcgis',
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/PDA/Schools/FeatureServer',
        "layers": None,
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=125',
        "department": 'Planning and Urban Design',
    },
    "floodplain": {
        "title": 'Floodplain',
        "type": 'arcgis',
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/Floodplain/MapServer',
        "layers": None,
        "portal_page": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/STLOUIS/Floodplain/MapServer',
        "department": 'Information Technology Services Agency',
    },
    "port-authority-district": {
        "title": 'Port Authority District',
        "type": 'arcgis',
        "service": 'https://maps8.stlouis-mo.gov/arcgis/rest/services/SLDC/Port_Authority_District_Boundary/FeatureServer',
        "layers": None,
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=55',
        "department": 'St. Louis Development Corporation',
    },
    "wards-2010": {
        "title": 'Ward Boundaries (2010)',
        "type": 'static',
        "url": 'https://static.stlouis-mo.gov/open-data/planning/wards/wards_2010.zip',
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=131',
        "department": 'Planning and Urban Design',
    },
    "land-use": {
        "title": 'Strategic Land Use Plan',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Strategic_Land_Use_Plan/FeatureServer',
        "layers": None,
        "portal_page": 'https://www.stlouis-mo.gov/data/datasets/dataset.cfm?id=78',
        "department": 'Planning and Urban Design',
    },
    "lead-service-lines": {
        "title": 'Lead Service Line Inventory',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/STLWD_LSLI__Read_Only_View/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=80c69343cc2d418fb1796a342a863aac',
        "department": 'Water Division',
    },
    "market-value-analysis": {
        "title": '2024 Market Value Analysis',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/2024_Market_Value_Analysis/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=e71e3ebca1f345a4b7db134d30c5d9ff',
        "department": 'Community Development Administration',
    },
    "vacancy-composite": {
        "title": 'Parcel Vacancy Composite',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/SLDC_SLDC_Tol_Def_Vac_NP/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=98a6f429617546be9d9b467c5ad1dafc',
        "department": 'St. Louis Development Corporation',
    },
    "polling-places": {
        "title": 'Polling Centers',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Polling_Centers_WFL1/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=87bc5cf8db58428295792e690397ed75',
        "department": 'Board of Election Commissioners',
    },
    "election-results-nov-2024": {
        "title": 'November 2024 Election Results by Precinct',
        "type": 'arcgis',
        # the geocoded dve layer carries no attribute data; the vote-totals
        # table has the real per-precinct, per-contest results (tabular,
        # joins election-precincts by precinct name).
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Nov24_Detailed_Vote_Totals_Test/FeatureServer',
        "layers": None,
        "table": True,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=6e72fa855cd445f7af37d79615f602d0',
        "department": 'Board of Election Commissioners',
    },
    "tornado-damage-2025": {
        "title": 'May 2025 Tornado Damage',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/NS_Tornado_Map_WFL1/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=d2f73ad3cd2b434b91c6eacaef94df32',
        "department": 'City Emergency Management Agency',
    },
    "flood-controls": {
        "title": 'Flood Controls',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Flood_Controls_WFL1/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=4a08499ad4054caca42215e4c51aac0e',
        "department": 'Board of Public Service',
    },
    "neighborhood-organizations": {
        "title": 'Neighborhood Organizations',
        "type": 'arcgis',
        "service": 'https://services6.arcgis.com/HZXbCkpCSqbGd0vK/arcgis/rest/services/Neighborhood_Organizations/FeatureServer',
        "layers": None,
        "portal_page": 'https://stlcity.maps.arcgis.com/home/item.html?id=ac198aeb9592458b8591c7258e719ad1',
        "department": 'Neighborhood Stabilization / CSB',
    },
    "property-sales": {
        "title": "Property Sales",
        "type": "static",
        "url": "https://www.stlouis-mo.gov/data/upload/data-files/prclsale.zip",
        "portal_page": PORTAL + "31",
        "department": "Assessor's Office",
    },
}
